// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsOgndBBnHSGb6Y7fnmRR-dQHmH13ylRA',
    appId: '1:1028675094288:web:810123fbc6287e3c364795',
    messagingSenderId: '1028675094288',
    projectId: 'sample-3952d',
    authDomain: 'sample-3952d.firebaseapp.com',
    storageBucket: 'sample-3952d.appspot.com',
    measurementId: 'G-6DWHZS2YWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7Vwrvi8kKzpRim5TP1tSNwSWP_W_mXM',
    appId: '1:1028675094288:android:3d1f3ca57acf6b56364795',
    messagingSenderId: '1028675094288',
    projectId: 'sample-3952d',
    storageBucket: 'sample-3952d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGibTB_nrNWMUyWoU55zimo4EyZkui9T0',
    appId: '1:1028675094288:ios:a2ceef7193387264364795',
    messagingSenderId: '1028675094288',
    projectId: 'sample-3952d',
    storageBucket: 'sample-3952d.appspot.com',
    iosBundleId: 'com.caringioStudent.in',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGibTB_nrNWMUyWoU55zimo4EyZkui9T0',
    appId: '1:1028675094288:ios:7548f52da2cae573364795',
    messagingSenderId: '1028675094288',
    projectId: 'sample-3952d',
    storageBucket: 'sample-3952d.appspot.com',
    iosBundleId: 'com.example.caringioStudent.RunnerTests',
  );
}
